In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv("data1.csv")
df

     Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.dtypes

Sepal Length    float64
Sepal Width     float64
Petal Length    float64
Petal Width     float64
Species          object
dtype: object

In [ ]:
df.info

<bound method DataFrame.info of      Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [ ]:
df.describe()

       Sepal Length  Sepal Width  Petal Length  Petal Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.notnull()

     Sepal Length  Sepal Width  Petal Length  Petal Width  Species
0            True         True          True         True     True
1            True         True          True         True     True
2            True         True          True         True     True
3            True         True          True         True     True
4            True         True          True         True     True
..            ...          ...           ...          ...      ...
145          True         True          True         True     True
146          True         True          True         True     True
147          True         True          True         True     True
148          True         True          True         True     True
149          True         True          True         True     True

[150 rows x 5 columns]

In [ ]:
df.shape

(150, 5)

In [ ]:
df.size

750

In [ ]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
df.head()

   Sepal Length  Sepal Width  Petal Length  Petal Width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.tail()

     Sepal Length  Sepal Width  Petal Length  Petal Width         Species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
df.tail(n=5)

     Sepal Length  Sepal Width  Petal Length  Petal Width         Species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
df.columns

Index(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Species'],
      dtype='object')

In [ ]:
df.columns.values

array(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Species'], dtype=object)

In [ ]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
df.sort_index(axis=1,ascending=True)

     Petal Length  Petal Width  Sepal Length  Sepal Width         Species
0             1.4          0.2           5.1          3.5     Iris-setosa
1             1.4          0.2           4.9          3.0     Iris-setosa
2             1.3          0.2           4.7          3.2     Iris-setosa
3             1.5          0.2           4.6          3.1     Iris-setosa
4             1.4          0.2           5.0          3.6     Iris-setosa
..            ...          ...           ...          ...             ...
145           5.2          2.3           6.7          3.0  Iris-virginica
146           5.0          1.9           6.3          2.5  Iris-virginica
147           5.2          2.0           6.5          3.0  Iris-virginica
148           5.4          2.3           6.2          3.4  Iris-virginica
149           5.1          1.8           5.9          3.0  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.iloc[4]

Sepal Length            5.0
Sepal Width             3.6
Petal Length            1.4
Petal Width             0.2
Species         Iris-setosa
Name: 4, dtype: object

In [ ]:
df[1:5]

   Sepal Length  Sepal Width  Petal Length  Petal Width      Species
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.iloc[:5,0:1]

   Sepal Length
0           5.1
1           4.9
2           4.7
3           4.6
4           5.0

In [ ]:
df.iloc[:8,:2]

   Sepal Length  Sepal Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6
5           5.4          3.9
6           4.6          3.4
7           5.0          3.4

In [ ]:
df.iloc[:,3]

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: Petal Width, Length: 150, dtype: float64

In [ ]:
df.iloc[3:5,0:2]

   Sepal Length  Sepal Width
3           4.6          3.1
4           5.0          3.6

In [ ]:
df.iloc[1,1]

3.0

In [ ]:
df['Sepal Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal Length, Length: 150, dtype: float64

In [ ]:
df['Sepal Length'].iloc[9]

4.9

In [ ]:
cols_2_4=df.columns[2:4]
df[cols_2_4]

     Petal Length  Petal Width
0             1.4          0.2
1             1.4          0.2
2             1.3          0.2
3             1.5          0.2
4             1.4          0.2
..            ...          ...
145           5.2          2.3
146           5.0          1.9
147           5.2          2.0
148           5.4          2.3
149           5.1          1.8

[150 rows x 2 columns]

In [ ]:
df[df.columns[2:4]].iloc[5:10]

   Petal Length  Petal Width
5           1.7          0.4
6           1.4          0.3
7           1.5          0.2
8           1.4          0.2
9           1.5          0.1

In [ ]:
df

     Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x=df.iloc[0:150,0:4]
x

     Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
x_scaled = min_max_scaler.fit_transform(x)
x_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.05555556, 0.125     , 0.05084746, 0.08333333],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.58333333, 0.33333333, 0.77966102, 0.83333333],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333]])

In [ ]:
df_normalized = pd.DataFrame(x_scaled)

df_normalized

            0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
df

     Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
label_encoder = preprocessing.LabelEncoder()
df['species'] = label_encoder.fit_transform(df['Species'])
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [ ]:
features_df = df.drop(columns=['Species'])
features_df

     Sepal Length  Sepal Width  Petal Length  Petal Width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
enc = preprocessing.OneHotEncoder()
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())

In [ ]:
df_encode = features_df.join(enc_df)
df_encode

,Sepal Length,Sepal Width,Petal Length,Petal Width,species,0,1,2
0,5.1,3.5,1.4,0.2,0,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,0,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,0,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,0,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,2,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,2,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,2,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,2,0.0,0.0,1.0

In [ ]:
df_encode.rename(columns = {0:'Iris-Setosa',1:'Iris-Versicolor',2:'Iris-virginica'}, inplace = True)
df_encode

,Sepal Length,Sepal Width,Petal Length,Petal Width,species,Iris-Setosa,Iris-Versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,0,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,0,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,0,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,0,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,2,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,2,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,2,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,2,0.0,0.0,1.0

In [ ]:
# Data Wrangling – Complete Theory and Code Explanation

# 1. What is Data Wrangling?

Data Wrangling means cleaning, organizing, transforming, and preparing raw data so it can be used for analysis or machine learning.

Raw data may contain:

* Missing values
* Duplicate values
* Wrong formats
* Unorganized columns
* Text data that algorithms cannot understand

Data wrangling converts raw data into clean and usable data.

---

# 2. Why is Data Wrangling Important?

Data wrangling is important because:

* Real-world data is usually messy.
* Machine learning algorithms require clean numeric data.
* It improves accuracy of analysis.
* It helps in visualization and prediction.
* It removes errors from datasets.

---

# 3. Main Steps in Data Wrangling

1. Collect Data
2. Load Data
3. Inspect Data
4. Clean Missing/Incorrect Data
5. Transform Data
6. Normalize or Scale Data
7. Encode Categorical Data
8. Save Clean Data

---

# 4. Libraries Required

Your notebook uses the following libraries:

## Pandas

Used for:

* Reading CSV files
* Handling tables/dataframes
* Data analysis

Import:

```python
import pandas as pd
```

---

## NumPy

Used for:

* Numerical operations
* Arrays and mathematical calculations

Import:

```python
import numpy as np
```

---

## Scikit-learn (sklearn)

Used for:

* Data preprocessing
* Machine learning utilities
* Scaling and encoding

Import:

```python
from sklearn import preprocessing
```

---

# 5. Requirements to Run This Program

## Software Required

You need:

1. Python
2. Jupyter Notebook OR Google Colab
3. Dataset file (data1.csv)

---

## Python Packages Required

Install using:

```bash
pip install pandas
pip install numpy
pip install scikit-learn
pip install notebook
```

OR install all together:

```bash
pip install pandas numpy scikit-learn notebook
```

---

# 6. Dataset Used

The notebook uses:

```python
data1.csv
```

This dataset contains Iris flower data.

Columns:

* Sepal Length
* Sepal Width
* Petal Length
* Petal Width
* Species

Species examples:

* Iris-setosa
* Iris-versicolor
* Iris-virginica

---

# 7. Complete Line-by-Line Code Explanation

---

# Step 1: Import Pandas

Code:

```python
import pandas as pd
```

Explanation:

* Imports Pandas library.
* `pd` is an alias (short name).
* Used for dataframe operations.

Example:

```python
pd.read_csv()
```

---

# Step 2: Import NumPy

Code:

```python
import numpy as np
```

Explanation:

* Imports NumPy library.
* `np` is alias.
* Used for mathematical calculations and arrays.

---

# Step 3: Read CSV File

Code:

```python
df = pd.read_csv("data1.csv")
df
```

Explanation:

* Reads CSV file.
* Stores data inside dataframe `df`.
* `df` displays dataset.

Meaning:

* `read_csv()` loads CSV file.
* Dataframe is table-like structure.

---

# Step 4: Check Data Types

Code:

```python
df.dtypes
```

Explanation:

* Shows datatype of every column.

Possible types:

* int64
* float64
* object

Example:

```python
Sepal Length    float64
Species         object
```

---

# Step 5: Dataset Information

Code:

```python
df.info
```

Explanation:

* Shows information about dataset.
* Displays:

  * Number of rows
  * Number of columns
  * Datatypes
  * Memory usage

Correct version should be:

```python
df.info()
```

---

# Step 6: Statistical Summary

Code:

```python
df.describe()
```

Explanation:

* Gives statistical summary.

Includes:

* Count
* Mean
* Standard deviation
* Minimum value
* Maximum value
* Quartiles

Useful for understanding data distribution.

---

# Step 7: Check Missing Values

Code:

```python
df.notnull()
```

Explanation:

* Checks whether values are NOT null.
* Returns:

  * True → value exists
  * False → missing value

Opposite function:

```python
df.isnull()
```

---

# Step 8: Dataset Shape

Code:

```python
df.shape
```

Explanation:

* Returns number of rows and columns.

Example:

```python
(150,5)
```

Meaning:

* 150 rows
* 5 columns

---

# Step 9: Dataset Size

Code:

```python
df.size
```

Explanation:

* Returns total number of elements.

Formula:

Rows × Columns

Example:

```python
150 × 5 = 750
```

---

# Step 10: Dataset Index

Code:

```python
df.index
```

Explanation:

* Displays row indexes.

Example:

```python
0,1,2,3...
```

---

# Step 11: Display First Rows

Code:

```python
df.head()
```

Explanation:

* Shows first 5 rows.

Useful for quick preview.

---

# Step 12: Display Last Rows

Code:

```python
df.tail()
```

Explanation:

* Shows last 5 rows.

---

# Step 13: Display Last N Rows

Code:

```python
df.tail(n=5)
```

Explanation:

* Shows last 5 rows.
* `n` can be changed.

Example:

```python
df.tail(n=10)
```

---

# Step 14: Display Column Names

Code:

```python
df.columns
```

Explanation:

* Shows all column names.

---

# Step 15: Display Column Names as Array

Code:

```python
df.columns.values
```

Explanation:

* Returns column names as NumPy array.

---

# Step 16: Display Index Again

Code:

```python
df.index
```

Explanation:

* Displays row indexes.

---

# Step 17: Sort Columns

Code:

```python
df.sort_index(axis=1, ascending=True)
```

Explanation:

* Sorts columns alphabetically.

Parameters:

## axis=1

Means columns.

## ascending=True

Sort in ascending order.

---

# Step 18: Select Row Using iloc

Code:

```python
df.iloc[4]
```

Explanation:

* Selects row at index 4.

`iloc` means:

* Integer-location based indexing.

---

# Step 19: Select Multiple Rows

Code:

```python
df[1:5]
```

Explanation:

* Selects rows from index 1 to 4.
* Last index excluded.

---

# Step 20: Select Specific Rows and Columns

Code:

```python
df.iloc[:5,0:1]
```

Explanation:

* First 5 rows.
* Column index 0 only.

Format:

```python
[row_range , column_range]
```

---

# Step 21: Select Rows and First Two Columns

Code:

```python
df.iloc[:8,:2]
```

Explanation:

* First 8 rows.
* First 2 columns.

---

# Step 22: Select Single Column

Code:

```python
df.iloc[:,3]
```

Explanation:

* Selects all rows.
* Column at index 3.

---

# Step 23: Select Small Data Portion

Code:

```python
df.iloc[3:5,0:2]
```

Explanation:

* Rows 3 and 4.
* Columns 0 and 1.

---

# Step 24: Select Single Value

Code:

```python
df.iloc[1,1]
```

Explanation:

* Selects value at:

  * Row index 1
  * Column index 1

---

# Step 25: Select Column by Name

Code:

```python
df['Sepal Length']
```

Explanation:

* Selects complete column.

---

# Step 26: Select Specific Value from Column

Code:

```python
df['Sepal Length'].iloc[9]
```

Explanation:

* Selects 10th value from column.

---

# Step 27: Store Selected Columns

Code:

```python
cols_2_4 = df.columns[2:4]
df[cols_2_4]
```

Explanation:

* Selects columns from index 2 to 3.
* Stores them in variable.

---

# Step 28: Select Rows and Stored Columns

Code:

```python
df[df.columns[2:4]].iloc[5:10]
```

Explanation:

* Selects columns 2 and 3.
* Then selects rows 5 to 9.

---

# Step 29: Display Dataframe

Code:

```python
df
```

Explanation:

* Displays full dataset.

---

# Step 30: Import Preprocessing and Create Scaler

Code:

```python
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()

x = df.iloc[0:150,0:4]
x
```

Explanation:

## preprocessing

Contains data transformation tools.

## MinMaxScaler()

Used for normalization.

Normalization means:

* Scaling data between 0 and 1.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"x' = \frac{x-x_{min}}{x_{max}-x_{min}}"}}

## x = df.iloc[0:150,0:4]

Selects:

* All 150 rows
* First 4 numeric columns

---

# Step 31: Normalize Data

Code:

```python
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
```

Explanation:

## fit_transform()

Performs two tasks:

1. Learns minimum and maximum values.
2. Transforms data into scaled values.

Output values become between:

0 and 1

Why normalization is important:

* Prevents large values from dominating.
* Improves ML model performance.

---

# Step 32: Convert Normalized Data into DataFrame

Code:

```python
df_normalized = pd.DataFrame(x_scaled)
df_normalized
```

Explanation:

* Converts normalized array into dataframe.
* Easier to read and analyze.

---

# Step 33: Display Unique Species

Code:

```python
df['Species'].unique()
```

Explanation:

* Shows unique flower categories.

Example:

```python
Iris-setosa
Iris-versicolor
Iris-virginica
```

---

# Step 34: Display Dataset Again

Code:

```python
df
```

Explanation:

* Displays dataframe.

---

# Step 35: Label Encoding

Code:

```python
label_encoder = preprocessing.LabelEncoder()

df['species'] = label_encoder.fit_transform(df['Species'])

df['species']
```

Explanation:

## Label Encoding

Converts text labels into numeric values.

Example:

```python
Iris-setosa      → 0
Iris-versicolor  → 1
Iris-virginica   → 2
```

Why needed?

* Machine learning models cannot understand text directly.

---

# Step 36: Drop Species Column

Code:

```python
features_df = df.drop(columns=['Species'])
features_df
```

Explanation:

* Removes original text column.
* Keeps numeric features only.

---

# Step 37: One Hot Encoding

Code:

```python
enc = preprocessing.OneHotEncoder()

enc_df = pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())
```

Explanation:

## One Hot Encoding

Converts categories into binary columns.

Example:

| Species    | Setosa | Versicolor | Virginica |
| ---------- | ------ | ---------- | --------- |
| Setosa     | 1      | 0          | 0         |
| Versicolor | 0      | 1          | 0         |

Why use One Hot Encoding?

* Avoids wrong ordering assumptions.
* Better for many ML models.

## toarray()

Converts sparse matrix into normal array.

---

# Step 38: Join Encoded Data

Code:

```python
df_encode = features_df.join(enc_df)
df_encode
```

Explanation:

* Combines original numeric features with encoded columns.

---

# Step 39: Rename Encoded Columns

Code:

```python
df_encode.rename(columns = {
0:'Iris-Setosa',
1:'Iris-Versicolor',
2:'Iris-virginica'
}, inplace = True)

df_encode
```

Explanation:

* Renames encoded columns.
* Makes dataset understandable.

## inplace=True

Changes original dataframe directly.

---

# 8. Important Concepts Used

## DataFrame

A table-like structure in Pandas.

---

## Indexing

Accessing rows and columns.

Methods:

* iloc → integer based
* loc → label based

---

## Normalization

Scaling data between fixed range.

Common range:

* 0 to 1

---

## Encoding

Converting categorical text data into numbers.

Types used:

* Label Encoding
* One Hot Encoding

---

# 9. Difference Between Label Encoding and One Hot Encoding

| Feature  | Label Encoding         | One Hot Encoding         |
| -------- | ---------------------- | ------------------------ |
| Output   | Single numeric column  | Multiple binary columns  |
| Example  | Cat=0 Dog=1            | Separate Cat/Dog columns |
| Best for | Ordered categories     | Unordered categories     |
| Risk     | Model may assume order | No order assumption      |

---

# 10. Real Life Applications of Data Wrangling

## Healthcare

Cleaning patient records.

## Banking

Fraud detection data preparation.

## E-commerce

Customer behavior analysis.

## Social Media

Sentiment analysis.

## Machine Learning

Preparing training datasets.

---

# 11. Advantages of Data Wrangling

* Improves data quality
* Removes errors
* Better ML accuracy
* Faster analysis
* Easier visualization

---

# 12. Viva Questions and Answers

## Q1. What is Data Wrangling?

Data wrangling is the process of cleaning and transforming raw data into usable format.

---

## Q2. Why do we use Pandas?

Pandas is used for data manipulation and analysis.

---

## Q3. What is a DataFrame?

A DataFrame is a table-like 2D data structure in Pandas.

---

## Q4. What is normalization?

Normalization scales data into fixed range like 0 to 1.

---

## Q5. Why is normalization important?

It prevents large values from dominating smaller values.

---

## Q6. What is Label Encoding?

Converting categorical labels into numeric form.

---

## Q7. What is One Hot Encoding?

Creating separate binary columns for each category.

---

## Q8. Difference between loc and iloc?

* loc → label based
* iloc → integer index based

---

## Q9. What is CSV?

CSV means Comma Separated Values file.

---

## Q10. What is Scikit-learn?

A Python library used for machine learning and preprocessing.

---

# 13. Short Summary

This notebook performs:

1. Dataset loading
2. Data inspection
3. Data selection
4. Data normalization
5. Label encoding
6. One hot encoding
7. Data transformation

Final result:

* Cleaned and machine-learning-ready dataset.






Process of Data Wrangling

Data Wrangling is the process of converting raw, messy data into clean and useful data for analysis or machine learning.

Steps in Data Wrangling
1. Data Collection

Collect data from different sources.

Sources can be:

CSV files
Databases
APIs
Websites
Excel files
Sensors

Example:

df = pd.read_csv("data.csv")

Purpose:

Gather raw data for processing.
2. Data Understanding / Inspection

Study the dataset to understand:

Number of rows and columns
Data types
Missing values
Errors

Common functions:

df.head()
df.info()
df.describe()
df.shape

Purpose:

Understand structure and quality of data.
3. Data Cleaning

Remove errors and unwanted data.

Includes:

Handling missing values
Removing duplicates
Fixing incorrect values
Correcting formats

Example:

df.drop_duplicates()
df.fillna(0)

Purpose:

Improve data quality.
4. Handling Missing Values

Real-world datasets often contain empty values.

Methods:

Remove rows/columns
Replace with mean/median/mode

Example:

df.fillna(df.mean())

Purpose:

Prevent errors during analysis.
5. Data Transformation

Convert data into useful format.

Includes:

Changing datatype
Combining columns
Splitting columns
Aggregation

Example:

df['Age'] = df['Age'].astype(int)

Purpose:

Make data suitable for processing.
6. Data Filtering and Selection

Select only important rows and columns.

Example:

df.iloc[:,0:3]

Purpose:

Reduce unnecessary data.
7. Data Normalization / Scaling

Scale numeric values into fixed range.

Common range:

0 to 1

Formula:

x
′
=
x
max
	​

−x
min
	​

x−x
min
	​

	​


Example:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

Purpose:

Improves machine learning performance.
8. Encoding Categorical Data

Machine learning models cannot understand text directly.

Convert text into numbers.

Types:

Label Encoding
One Hot Encoding

Example:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

Purpose:

Convert categorical data into numeric form.
9. Data Validation

Check whether cleaned data is correct.

Verify:

No missing values
Correct formats
No duplicates

Example:

df.isnull().sum()

Purpose:

Ensure data accuracy.
10. Data Storage

Save cleaned data.

Formats:

CSV
Excel
Database

Example:

df.to_csv("cleaned_data.csv")

Purpose:

Use cleaned data later for analysis or ML.
Complete Flow of Data Wrangling
Raw Data
   ↓
Collect Data
   ↓
Inspect Data
   ↓
Clean Data
   ↓
Handle Missing Values
   ↓
Transform Data
   ↓
Normalize/Scale Data
   ↓
Encode Categorical Data
   ↓
Validate Data
   ↓
Store Clean Data
Real Life Example
Online Shopping Website

Raw Data:

Customer names
Missing phone numbers
Wrong prices
Duplicate orders

Data Wrangling does:

Removes duplicates
Fills missing values
Corrects formats
Converts categories into numbers

Result:

Clean dataset for recommendation systems and sales analysis.
Advantages of Data Wrangling
Improves data quality
Removes errors
Better machine learning accuracy
Easier visualization
Faster analysis
Viva Questions
Q1. What is Data Wrangling?

Data wrangling is the process of cleaning and transforming raw data into useful format.

Q2. Why is Data Wrangling important?

Because real-world data is usually incomplete and messy.

Q3. What are the major steps in Data Wrangling?
Collection
Inspection
Cleaning
Transformation
Normalization
Encoding
Validation
Storage
Q4. What is normalization?

Scaling values into fixed range like 0 to 1.

Q5. Why do we encode categorical data?

Machine learning models cannot understand text directly.





What is pip?

pip is the package manager for Python.

It is used to:

Install Python libraries/packages
Update libraries
Remove libraries
Manage external modules

Full form of pip:

PIP = Preferred Installer Program
Why is pip Used?

Python has many libraries like:

NumPy
Pandas
Matplotlib
Scikit-learn

These libraries are not always included by default.

pip helps download and install them from the Python Package Index.

Example

If you want to use Pandas:

import pandas as pd

First you must install it using pip:

pip install pandas
What Happens Internally?

When you run:

pip install pandas

pip:

Connects to Python package repository
Downloads Pandas
Installs it into your Python environment
Makes it available for import
Common pip Commands
1. Install Package
pip install numpy

Installs NumPy library.

2. Install Multiple Packages
pip install pandas numpy matplotlib
3. Upgrade Package
pip install --upgrade pandas

Updates package to latest version.

4. Remove Package
pip uninstall pandas

Deletes package.

5. Check Installed Packages
pip list

Shows all installed libraries.

6. Check Package Information
pip show pandas

Displays:

Version
Location
Dependencies
Why pip is Important in Data Wrangling

Data wrangling requires libraries like:

Library	Purpose
Pandas	Data handling
NumPy	Mathematical operations
Scikit-learn	Scaling & encoding
Matplotlib	Visualization

Install them using pip:

pip install pandas numpy scikit-learn matplotlib
Real Life Analogy

Think of Python as a mobile phone.

Libraries are apps.

pip is like the Play Store/App Store used to install apps.

Difference Between Python and pip
Python	pip
Programming language	Package manager
Runs code	Installs libraries
Creates programs	Manages packages
Where pip Installs Packages?

Usually inside:

Python/Lib/site-packages

That is where external libraries are stored.

How to Check if pip is Installed?

Run:

pip --version

Example output:

pip 25.0 from ...
If pip is Not Working

Use:

python -m pip install pandas

or

py -m pip install pandas
Viva Questions
Q1. What is pip?

pip is Python’s package manager used to install external libraries.

Q2. Why do we use pip?

To install and manage Python packages.

Q3. What is the command to install Pandas?
pip install pandas
Q4. What is a package?

A package is a collection of Python modules/functions.

Q5. What does pip install do?

It downloads and installs libraries from the Python Package Index.





Python Libraries Used in Data Science and Data Wrangling
These are very important Python libraries used in:


Data Wrangling


Data Analysis


Machine Learning


Visualization



1. NumPy
What is NumPy?
NumPy is a Python library used for:


Numerical operations


Arrays


Mathematical calculations


Matrix operations


Full form:
Numerical Python

Why NumPy is Used?
Python lists are slower for calculations.
NumPy provides:


Faster execution


Less memory usage


Mathematical functions



Main Feature of NumPy
ndarray (N-dimensional Array)
NumPy stores data in arrays.
Example:
import numpy as nparr = np.array([1,2,3,4])print(arr)
Output:
[1 2 3 4]

Common NumPy Operations
Array Creation
np.array([1,2,3])

Zeros Array
np.zeros((2,2))
Creates matrix filled with 0.

Ones Array
np.ones((3,3))
Creates matrix filled with 1.

Mathematical Operations
a = np.array([1,2,3])b = np.array([4,5,6])print(a+b)
Output:
[5 7 9]

Applications of NumPy


Machine Learning


Scientific computing


Image processing


Matrix calculations


Statistics



Advantages of NumPy


Very fast


Efficient memory usage


Supports vector operations


Easy mathematical computations



2. Pandas
What is Pandas?
pandas is a Python library used for:


Data handling


Data analysis


Data wrangling


Working with tables



Why Pandas is Used?
Real-world data is stored in:


CSV files


Excel sheets


Databases


Pandas makes handling such data easy.

Main Data Structures in Pandas
Series
1-dimensional data.
Example:
s = pd.Series([1,2,3])

DataFrame
2-dimensional table.
Example:
import pandas as pddf = pd.DataFrame({    'Name':['Ali','Sara'],    'Age':[20,21]})print(df)

Common Pandas Operations
Read CSV File
pd.read_csv("data.csv")

Display First Rows
df.head()

Dataset Information
df.info()

Statistical Summary
df.describe()

Missing Values
df.isnull()

Applications of Pandas


Data cleaning


Data wrangling


Business analytics


Data preprocessing


Financial analysis



Advantages of Pandas


Easy table handling


Fast data analysis


Supports large datasets


Simple syntax



3. Matplotlib
What is Matplotlib?
Matplotlib is a Python library used for:


Data visualization


Graph plotting


Charts



Why Matplotlib is Used?
Graphs help understand:


Trends


Comparisons


Patterns


Relationships



Common Types of Graphs


Line graph


Bar chart


Pie chart


Histogram


Scatter plot



Basic Example
import matplotlib.pyplot as pltx = [1,2,3]y = [2,4,6]plt.plot(x,y)plt.show()

Explanation
plt.plot()
Draws graph.
plt.show()
Displays graph.

Applications of Matplotlib


Data visualization


Scientific graphs


Business reports


Machine learning analysis



Advantages of Matplotlib


Easy plotting


Many chart types


Customizable graphs


Good for analysis



4. Scikit-learn
What is Scikit-learn?
scikit-learn is a Python library used for:


Machine Learning


Data preprocessing


Model training


Prediction



Why Scikit-learn is Used?
It provides ready-made machine learning algorithms.
No need to write algorithms from scratch.

Common Tasks in Scikit-learn


Classification


Regression


Clustering


Normalization


Encoding



Example: Normalization
from sklearn.preprocessing import MinMaxScalerscaler = MinMaxScaler()
Used to scale values between 0 and 1.
Formula:
x′=x−xminxmax−xminx' = \frac{x-x_{min}}{x_{max}-x_{min}}x′=xmax​−xmin​x−xmin​​

Example: Label Encoding
from sklearn.preprocessing import LabelEncoderencoder = LabelEncoder()
Converts text into numbers.
Example:
Cat → 0Dog → 1

Applications of Scikit-learn


Spam detection


Recommendation systems


Fraud detection


Prediction systems


AI models



Advantages of Scikit-learn


Simple syntax


Many ML algorithms


Easy preprocessing


Fast implementation



Difference Between These Libraries
LibraryMain PurposeNumPyNumerical calculationsPandasData handling & wranglingMatplotlibData visualizationScikit-learnMachine learning

How They Work Together
Example flow:
NumPy → Mathematical operations       ↓Pandas → Data cleaning and handling       ↓Matplotlib → Visualization       ↓Scikit-learn → Machine learning

Real Life Example
Student Result Analysis System
NumPy
Calculates averages.
Pandas
Stores student records.
Matplotlib
Creates result graphs.
Scikit-learn
Predicts student performance.

Installation Commands
Install all libraries:
pip install numpy pandas matplotlib scikit-learn

Viva Questions
Q1. What is NumPy?
NumPy is a library for numerical and array operations.

Q2. What is Pandas?
Pandas is a library for data handling and analysis.

Q3. What is Matplotlib?
Matplotlib is a library for plotting graphs and charts.

Q4. What is Scikit-learn?
Scikit-learn is a machine learning and preprocessing library.

Q5. Which library is used for visualization?
Matplotlib.

Q6. Which library is used for dataframes?
Pandas.

Q7. Which library is used for arrays?
NumPy.

Q8. Which library is used for machine learning?
Scikit-learn.





What is MinMaxScaler?
MinMaxScaler is a preprocessing tool from scikit-learn used to normalize data.
It scales numeric values into a fixed range.
Usually the range is:
0 to 1

Why Do We Use MinMaxScaler?
Different columns may have very different values.
Example:
AgeSalary20200002550000
Problem:


Salary values are much larger than Age values.


Machine learning models may give more importance to Salary.


Solution:


Scale both columns into same range using MinMaxScaler.



Formula Used
x′=x−xminxmax−xminx' = \frac{x-x_{min}}{x_{max}-x_{min}}x′=xmax​−xmin​x−xmin​​
Where:
SymbolMeaningxOriginal valuexminMinimum valuexmaxMaximum valuex'Scaled value

Working Example
Suppose values are:
[10, 20, 30, 40]
Here:


Minimum = 10


Maximum = 40


Now scale value 20:
x′=20−1040−10x' = \frac{20-10}{40-10}x′=40−1020−10​
Result:
10/30 = 0.33
Similarly:
OriginalScaled100200.33300.66401

Code Explanation
Code
from sklearn import preprocessingmin_max_scaler = preprocessing.MinMaxScaler()

Line-by-Line Explanation
Line 1
from sklearn import preprocessing
Explanation:


Imports preprocessing module from Scikit-learn.


Preprocessing contains tools for:


Scaling


Encoding


Normalization





Line 2
min_max_scaler = preprocessing.MinMaxScaler()
Explanation:


Creates object of MinMaxScaler class.


This object will normalize data.


min_max_scaler is variable name.

Full Example
from sklearn.preprocessing import MinMaxScalerimport pandas as pddata = [[10],[20],[30],[40]]scaler = MinMaxScaler()scaled_data = scaler.fit_transform(data)print(scaled_data)

Output
[[0.        ] [0.33333333] [0.66666667] [1.        ]]

What Does fit_transform() Do?
fit()
Learns:


Minimum value


Maximum value



transform()
Applies scaling formula.

fit_transform()
Performs both together.

Why MinMaxScaler is Important in Machine Learning?
Many ML algorithms work better when data is scaled.
Examples:


KNN


Neural Networks


SVM


Gradient Descent


Benefits:


Faster training


Better accuracy


Stable calculations



Advantages of MinMaxScaler


Simple normalization


Keeps relationships between values


Values remain in fixed range


Improves ML performance



Disadvantage
Sensitive to outliers.
Example:
If one value is extremely large, scaling becomes distorted.

Difference Between Normalization and Standardization
| Feature | MinMaxScaler | StandardScaler |
|---|---|
| Range | 0 to 1 | Mean = 0 |
| Formula Type | Normalization | Standardization |
| Sensitive to Outliers | Yes | Less |

Real Life Example
Exam Marks
Original Marks:
[45, 60, 90]
Different subjects may have different maximum marks.
MinMaxScaler converts them into same scale for fair comparison.

Viva Questions
Q1. What is MinMaxScaler?
MinMaxScaler is used to normalize data between 0 and 1.

Q2. Why do we use MinMaxScaler?
To scale features into same range and improve ML performance.

Q3. Which library provides MinMaxScaler?
scikit-learn

Q4. What does fit_transform() do?
It learns min/max values and transforms data.

Q5. What is normalization?
Scaling data into fixed range like 0 to 1.