In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("data2.csv")

In [ ]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [ ]:
df.isnull()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,False,True

In [ ]:
series = pd.isnull(df["math score"])
df[series]

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
7,male,NaN,65,67.0,49.0,1,Pune

In [ ]:
df.notnull()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,True,True,True,True,True,True,True
1,True,True,True,True,False,True,True
2,True,True,True,True,True,True,True
3,True,True,True,False,True,True,True
4,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True
7,True,False,True,True,True,True,True
8,True,True,True,True,True,True,False

In [ ]:
series1 = pd.notnull(df["math score"])
df[series1]

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
8,male,5,77,89.0,55.0,0,NaN

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
newdf=df
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,0,72,72,74.0,78.0,1,Pune
1,0,69,90,88.0,NaN,2,na
2,0,90,95,93.0,74.0,2,Nashik
3,1,47,57,NaN,78.0,1,Na
4,1,na,78,75.0,81.0,3,Pune
5,0,71,Na,78.0,70.0,4,na
6,1,12,44,52.0,12.0,2,Nashik
7,1,NaN,65,67.0,49.0,1,Pune
8,1,5,77,89.0,55.0,0,NaN

In [ ]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [ ]:
missing_values = ["Na", "na"," "]
df = pd.read_csv("data2.csv", na_values = missing_values)
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,72.0,74.0,78.0,1,Pune
1,female,69.0,90.0,88.0,NaN,2,NaN
2,female,90.0,95.0,93.0,74.0,2,Nashik
3,male,47.0,57.0,NaN,78.0,1,NaN
4,male,NaN,78.0,75.0,81.0,3,Pune
5,female,71.0,NaN,78.0,70.0,4,NaN
6,male,12.0,44.0,52.0,12.0,2,Nashik
7,male,NaN,65.0,67.0,49.0,1,Pune
8,male,5.0,77.0,89.0,55.0,0,NaN

In [ ]:
ndf=df
ndf.fillna(0)
ndf

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.0,78.0,1,Pune
1,female,69.000000,90.0,88.0,NaN,2,NaN
2,female,90.000000,95.0,93.0,74.0,2,Nashik
3,male,47.000000,57.0,NaN,78.0,1,NaN
4,male,52.285714,78.0,75.0,81.0,3,Pune
5,female,71.000000,74.5,78.0,70.0,4,NaN
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune
8,male,5.000000,77.0,89.0,55.0,0,NaN

In [ ]:
df['reading score'] = df['reading score'].fillna(df['reading score'].median())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,72.0,74.0,78.0,1,Pune
1,female,69.0,90.0,88.0,NaN,2,NaN
2,female,90.0,95.0,93.0,74.0,2,Nashik
3,male,47.0,57.0,NaN,78.0,1,NaN
4,male,NaN,78.0,75.0,81.0,3,Pune
5,female,71.0,74.5,78.0,70.0,4,NaN
6,male,12.0,44.0,52.0,12.0,2,Nashik
7,male,NaN,65.0,67.0,49.0,1,Pune
8,male,5.0,77.0,89.0,55.0,0,NaN

In [ ]:
df['math score'] = df['math score'].fillna(df['math score'].mean())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.0,78.0,1,Pune
1,female,69.000000,90.0,88.0,NaN,2,NaN
2,female,90.000000,95.0,93.0,74.0,2,Nashik
3,male,47.000000,57.0,NaN,78.0,1,NaN
4,male,52.285714,78.0,75.0,81.0,3,Pune
5,female,71.000000,74.5,78.0,70.0,4,NaN
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune
8,male,5.000000,77.0,89.0,55.0,0,NaN

In [ ]:
df['writing score'] = df['writing score'].fillna(df['writing score'].std())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,72.0,74.000000,78.0,1,Pune
1,female,69.0,90.0,88.000000,NaN,2,NaN
2,female,90.0,95.0,93.000000,74.0,2,Nashik
3,male,47.0,57.0,13.416408,78.0,1,NaN
4,male,NaN,78.0,75.000000,81.0,3,Pune
5,female,71.0,74.5,78.000000,70.0,4,NaN
6,male,12.0,44.0,52.000000,12.0,2,Nashik
7,male,NaN,65.0,67.000000,49.0,1,Pune
8,male,5.0,77.0,89.000000,55.0,0,NaN

In [ ]:
df['Placement Score'] = df['Placement Score'].fillna(df['Placement Score'].min())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,72.0,74.000000,78.0,1,Pune
1,female,69.0,90.0,88.000000,12.0,2,NaN
2,female,90.0,95.0,93.000000,74.0,2,Nashik
3,male,47.0,57.0,13.416408,78.0,1,NaN
4,male,NaN,78.0,75.000000,81.0,3,Pune
5,female,71.0,74.5,78.000000,70.0,4,NaN
6,male,12.0,44.0,52.000000,12.0,2,Nashik
7,male,NaN,65.0,67.000000,49.0,1,Pune
8,male,5.0,77.0,89.000000,55.0,0,NaN

In [ ]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,72.0,74.000000,78.0,1,Pune
1,female,69.0,90.0,88.000000,12.0,2,NaN
2,female,90.0,95.0,93.000000,74.0,2,Nashik
3,male,47.0,57.0,13.416408,78.0,1,NaN
4,male,NaN,78.0,75.000000,81.0,3,Pune
5,female,71.0,74.5,78.000000,70.0,4,NaN
6,male,12.0,44.0,52.000000,12.0,2,Nashik
7,male,NaN,65.0,67.000000,49.0,1,Pune
8,male,5.0,77.0,89.000000,55.0,0,NaN

In [ ]:
ndf.replace(to_replace = np.nan, value = -99)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.0,78.0,1,Pune
1,female,69.000000,90.0,88.0,-99.0,2,-99
2,female,90.000000,95.0,93.0,74.0,2,Nashik
3,male,47.000000,57.0,-99.0,78.0,1,-99
4,male,52.285714,78.0,75.0,81.0,3,Pune
5,female,71.000000,74.5,78.0,70.0,4,-99
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune
8,male,5.000000,77.0,89.0,55.0,0,-99

In [ ]:
ndf.dropna()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.0,78.0,1,Pune
2,female,90.000000,95.0,93.0,74.0,2,Nashik
4,male,52.285714,78.0,75.0,81.0,3,Pune
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune

In [ ]:
ndf.dropna(how = 'all')

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.000000,78.0,1,Pune
1,female,69.000000,90.0,88.000000,12.0,2,NaN
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.416408,78.0,1,NaN
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,74.5,78.000000,70.0,4,NaN
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,NaN

In [ ]:
ndf.dropna(axis = 1)

,gender,reading score,writing score,Placement Score,placement offer count
0,female,72.0,74.000000,78.0,1
1,female,90.0,88.000000,12.0,2
2,female,95.0,93.000000,74.0,2
3,male,57.0,13.416408,78.0,1
4,male,78.0,75.000000,81.0,3
5,female,74.5,78.000000,70.0,4
6,male,44.0,52.000000,12.0,2
7,male,65.0,67.000000,49.0,1
8,male,77.0,89.000000,55.0,0

In [ ]:
new_data = ndf.dropna(axis = 0, how ='any')
new_data

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,72.0,74.0,78.0,1,Pune
2,female,90.000000,95.0,93.0,74.0,2,Nashik
4,male,52.285714,78.0,75.0,81.0,3,Pune
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune

In [ ]:
df=pd.read_csv("data22.csv")
df

,math score,reading score,writing score,placement score,placement offer count,club join year
0,80,68,70,89,3,2019
1,71,61,85,91,3,2019
2,79,16,87,77,2,2018
3,61,77,74,76,2,2020
4,78,71,67,90,3,2019
5,73,68,90,80,2,2019
6,77,62,70,35,2,2020
7,74,45,80,12,1,2019
8,76,60,79,77,2,2020
9,75,65,85,87,3,2018
10,160,67,12,83,2,2020
11,79,72,88,180,2,2019
12,80,80,78,94,3,2021
13,78,69,71,90,3,2019
14,75,1,71,81,2,2019
15,78,62,79,93,3,2021
16,86,78,80,88,3,2019
17,80,74,23,76,2,2021
18,75,62,86,87,3,2019
19,82,70,87,94,3,2019
20,69,65,84,35,1,2018
21,100,77,70,91,3,2018
22,72,60,78,94,3,2019
23,74,65,71,84,2,2019
24,75,77,83,77,2,2020
25,180,67,63,75,3,2021
26,72,120,70,84,2,2021
27,71,79,88,85,3,2021
28,120,73,71,94,3,2019

In [ ]:
print(np.where(df['math score']>90))
print(np.where(df['reading score']<25))
print(np.where(df['writing score']<30))

(array([10, 21, 25, 28]),)
(array([ 2, 14]),)
(array([10, 17]),)

In [ ]:
from scipy import stats

In [ ]:
z = np.abs(stats.zscore(df['math score']))

In [ ]:
print(z)

0     0.175646
1     0.528288
2     0.214828
3     0.920112
4     0.254010
5     0.449923
6     0.293193
7     0.410740
8     0.332375
9     0.371558
10    2.958952
11    0.214828
12    0.175646
13    0.254010
14    0.371558
15    0.254010
16    0.059449
17    0.175646
18    0.371558
19    0.097281
20    0.606653
21    0.608004
22    0.489105
23    0.410740
24    0.371558
25    3.742601
26    0.489105
27    0.528288
28    1.391653
Name: math score, dtype: float64

In [ ]:
threshold = 0.18

In [ ]:
sample_outliers = np.where(z <threshold)
sample_outliers

(array([ 0, 12, 16, 17, 19]),)

In [ ]:
sorted_rscore= sorted(df['reading score'])
sorted_rscore

[1,
 16,
 45,
 60,
 60,
 61,
 62,
 62,
 62,
 65,
 65,
 65,
 67,
 67,
 68,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 77,
 77,
 77,
 78,
 79,
 80,
 120]

In [ ]:
q1 = np.percentile(sorted_rscore, 25)

In [ ]:
q3 = np.percentile(sorted_rscore, 75)
print(q1,q3)

62.0 74.0

In [ ]:
IQR = q3-q1

In [ ]:
lwr_bound = q1-(1.5*IQR)
upr_bound = q3+(1.5*IQR)
print(lwr_bound, upr_bound)

44.0 92.0

In [ ]:
r_outliers = []
for i in sorted_rscore:
  if (i<lwr_bound or i>upr_bound):
    r_outliers.append(i)
  print(r_outliers)

[1]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16, 120]

In [ ]:
CHATGPT LINK TO STUDY

https://chatgpt.com/share/6a05d9cb-7160-8324-bb38-506512da552d

In [ ]:
Data Wrangling – Complete Theory + Steps + Code Explanation

Data Wrangling is also called Data Cleaning or Data Preprocessing.

It is the process of:

collecting raw data,
cleaning it,
converting it into a useful format,
and preparing it for analysis or machine learning.
1. Why Data Wrangling is Needed?

Real-world data is usually:

incomplete,
noisy,
duplicated,
inconsistent,
or contains errors.

Example:

Name	Math Score
Ali	90
Sara	NaN
John	85

Here:

NaN means missing value.
We must clean it before analysis.

Without data wrangling:

ML models give wrong predictions,
graphs become inaccurate,
analysis becomes unreliable.
2. Steps of Data Wrangling
Step 1: Data Collection

Collect data from:

CSV files
Excel
Databases
APIs
Sensors
Websites

Example:

df = pd.read_csv("data.csv")
Step 2: Understanding Data

Check:

rows and columns
data types
missing values
statistics

Example:

df.head()
df.info()
df.describe()
Step 3: Handling Missing Values

Missing values can be:

removed,
replaced,
or estimated.

Methods:

fill with mean
fill with median
fill with mode
fill with 0
drop rows/columns
Step 4: Handling Categorical Data

Machine learning algorithms understand numbers, not text.

Example:

Gender
Male
Female

Convert into:

Gender
1
0

Using:

LabelEncoder()
Step 5: Removing Duplicates

Duplicate rows create wrong analysis.

Example:

df.drop_duplicates()
Step 6: Detecting Outliers

Outliers are abnormal values.

Example:

Marks = 10, 20, 30, 500

500 is an outlier.

Methods:

Z-score
IQR (Inter Quartile Range)
Step 7: Data Transformation

Convert data into proper format:

scaling
normalization
encoding
3. Requirements to Run Your Notebook

Your notebook requires:

Software Required
Python

Install Python.

Jupyter Notebook

Used to run .ipynb files.

You can install:

pip install notebook

Run:

jupyter notebook
4. Libraries Required

Your notebook uses these libraries:

Pandas

Used for:

reading CSV,
handling tables,
cleaning data.

Install:

pip install pandas
NumPy

Used for:

arrays,
mathematical operations.

Install:

pip install numpy
Scikit-learn

Used for:

Label Encoding,
Machine Learning utilities.

Install:

pip install scikit-learn
SciPy

Used for:

statistical operations,
z-score.

Install:

pip install scipy
5. Complete Line-by-Line Code Explanation
Cell 1
import pandas as pd
import numpy as np
Explanation
import pandas as pd

Imports Pandas library.

pd is alias name.

Used for:

tables,
CSV files,
cleaning data.
import numpy as np

Imports NumPy library.

Used for:

arrays,
numerical calculations,
NaN values.
Cell 2
df = pd.read_csv("data2.csv")
Explanation

Reads CSV file.

pd.read_csv() → reads CSV.
df → DataFrame (table structure).
Cell 3
df

Displays dataset.

Cell 4
df.isnull()
Explanation

Checks missing values.

Returns:

True → missing value
False → value exists
Cell 5
series = pd.isnull(df["math score"])
df[series]
Explanation
Line 1
pd.isnull(df["math score"])

Checks missing values only in "math score" column.

Line 2
df[series]

Displays rows where math score is missing.

Cell 6
df.notnull()

Opposite of isnull().

True → value exists
False → missing
Cell 7
series1 = pd.notnull(df["math score"])
df[series1]

Shows rows where math score exists.

Cell 8
from sklearn.preprocessing import LabelEncoder

Imports LabelEncoder.

Used to convert text into numbers.

le = LabelEncoder()

Creates LabelEncoder object.

df['gender'] = le.fit_transform(df['gender'])

Converts:

Male → 1
Female → 0

Machine learning needs numeric data.

newdf = df

Creates copy reference.

Cell 9
missing_values = ["Na", "na", " "]

Defines custom missing values.

df = pd.read_csv("data2.csv", na_values=missing_values)

Treats:

"Na"
"na"
blank spaces

as missing values (NaN).

Cell 10
ndf = df
ndf.fillna(0)
Explanation

Replaces missing values with 0.

Cell 11
df['reading score'] = df['reading score'].fillna(df['reading score'].median())
Explanation

Missing values replaced with median.

Why median?

Median works well when outliers exist.

Cell 12
df['math score'] = df['math score'].fillna(df['math score'].mean())
Explanation

Missing values replaced with mean.

Cell 13
df['writing score'] = df['writing score'].fillna(df['writing score'].std())
Explanation

Missing values replaced using standard deviation.

std()

Measures spread of data.

Cell 14
df['Placement Score'] = df['Placement Score'].fillna(df['Placement Score'].min())
Explanation

Missing values replaced with minimum value.

Cell 16
ndf.replace(to_replace=np.nan, value=-99)
Explanation

Replaces all NaN values with -99.

Used sometimes in ML.

Cell 17
ndf.dropna()
Explanation

Removes rows containing missing values.

Cell 18
ndf.dropna(how='all')

Removes rows only if ALL values are missing.

Cell 19
ndf.dropna(axis=1)
Explanation

Removes columns containing missing values.

axis=1

Means columns.

Cell 20
new_data = ndf.dropna(axis=0, how='any')

Removes rows having even one missing value.

Cell 21
df = pd.read_csv("data22.csv")

Loads second dataset.

Cell 22
print(np.where(df['math score'] > 90))
Explanation

Finds indexes where math score > 90.

print(np.where(df['reading score'] < 25))

Finds reading scores less than 25.

print(np.where(df['writing score'] < 30))

Finds writing scores less than 30.

Used for outlier detection.

Cell 23
from scipy import stats

Imports statistical functions.

Cell 24
z = np.abs(stats.zscore(df['math score']))
Z-Score Method

Used to detect outliers.

Formula
z=
σ
x−μ
	​

x
μ
σ
z=
σ
x−μ
	​

≈1.2
Φ(z)≈88.5%

Where:

x = data value
μ = mean
σ = standard deviation
stats.zscore()

Calculates z-score.

np.abs()

Converts negative values into positive.

Cell 26
threshold = 0.18

Sets limit for outlier detection.

Usually:

z > 3 → outlier
Cell 27
sample_outliers = np.where(z < threshold)

Finds values below threshold.

Cell 28
sorted_rscore = sorted(df['reading score'])

Sorts reading scores.

Cell 29
q1 = np.percentile(sorted_rscore, 25)

Finds first quartile (25%).

Cell 30
q3 = np.percentile(sorted_rscore, 75)

Finds third quartile (75%).

IQR Method
Formula

IQR=Q
3
	​

−Q
1
	​


Cell 31
IQR = q3 - q1

Calculates Interquartile Range.

Cell 32
lwr_bound = q1 - (1.5 * IQR)
upr_bound = q3 + (1.5 * IQR)

Calculates lower and upper bounds.

Values outside range are outliers.

Cell 33
r_outliers = []

Creates empty list.

for i in sorted_rscore:

Loops through values.

if(i < lwr_bound or i > upr_bound):

Checks outlier condition.

r_outliers.append(i)

Stores outlier.




7. Real-Life Applications of Data Wrangling
Healthcare data cleaning
Bank fraud detection
Stock market analysis
Customer analysis
AI & Machine Learning
Data visualization
Recommendation systems
8. Simple Definition for Viva

“Data wrangling is the process of cleaning, transforming, organizing, and preparing raw data into a useful format for analysis and machine learning.”



Viva Questions and Answers – Data Wrangling
Basic Questions
1. What is Data Wrangling?

Data wrangling is the process of:

cleaning,
organizing,
transforming,
and preparing raw data

into a useful format for analysis or machine learning.

Simple Viva Definition

“Data wrangling converts raw and messy data into clean and structured data.”

2. Why is Data Cleaning Important?

Real-world data contains:

missing values,
duplicate values,
incorrect data,
noisy data,
outliers.

If data is not cleaned:

analysis becomes wrong,
machine learning accuracy decreases,
graphs become misleading.
Example

If student marks contain:

[45, 67, 500]

500 is incorrect and affects average.

3. Difference Between Cleaning and Preprocessing
Data Cleaning	Data Preprocessing
Removes errors	Converts data for ML
Handles missing values	Scaling and normalization
Removes duplicates	Feature transformation
Improves data quality	Improves model performance
Simple Difference
Cleaning → fixes bad data.
Preprocessing → prepares data for machine learning.
4. What is Missing Data?

Missing data means some values are absent from dataset.

Example
Name	Marks
Ali	90
Sara	NaN

Sara’s marks are missing.

5. What is NaN?

NaN means:

“Not a Number”

It represents missing or undefined values.

Example
import numpy as np
np.nan

Used in Pandas and NumPy datasets.

Pandas Questions
6. What is DataFrame?

A DataFrame is a:

2-dimensional table structure
made of rows and columns.

It is provided by Pandas library.

Example
Name	Age
Ali	20
Sara	21
Code
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Age": [20, 21]
})
7. Difference Between isnull() and notnull()
isnull()	notnull()
Checks missing values	Checks existing values
Returns True for NaN	Returns True for valid data
Example
df.isnull()

Output:

Marks
False
True
Example
df.notnull()

Output:

Marks
True
False
8. Difference Between fillna() and dropna()
fillna()	dropna()
Replaces missing values	Removes missing values
Keeps data	Deletes rows/columns
Example of fillna()
df.fillna(0)

Replaces NaN with 0.

Example of dropna()
df.dropna()

Deletes rows containing NaN.

9. What Does axis=1 Mean?

In Pandas:

Axis	Meaning
axis=0	Rows
axis=1	Columns
Example
df.dropna(axis=1)

Removes columns having missing values.

Outlier Questions
10. What are Outliers?

Outliers are abnormal or extreme values that are very different from other data values.

Example
[10, 12, 15, 18, 500]

500 is an outlier.

11. Explain Z-Score

Z-score measures:

how far a data point is from mean
in terms of standard deviation.
Formula
z=
σ
x−μ
	​

x
μ
σ
z=
σ
x−μ
	​

≈1.2
Φ(z)≈88.5%

Where:

x = data value
μ = mean
σ = standard deviation
Interpretation
Z-score	Meaning
z = 0	value equals mean
z > 3	possible outlier
z < -3	possible outlier
Example

If class average is 50 and student got 90:

Z-score tells how unusual 90 is.
12. Explain IQR Method

IQR means:

Inter Quartile Range

It measures spread of middle 50% data.

Formula

IQR=Q
3
	​

−Q
1
	​


Where:

Q1 = 25th percentile
Q3 = 75th percentile
Outlier Limits
Lower Bound

Lower Bound=Q
1
	​

−1.5(IQR)

Upper Bound

Upper Bound=Q
3
	​

+1.5(IQR)

Values outside these bounds are outliers.

13. Why Detect Outliers?

Outliers can:

reduce model accuracy,
affect averages,
create wrong analysis,
produce misleading graphs.
Example

Salary dataset:

[25000, 27000, 26000, 1000000]

1000000 changes average heavily.

Short Viva Answers (One-Line)
Question	                    One-Line Answer
What is data wrangling?	      Process of cleaning and preparing data.
What is NaN?	                Missing or undefined value.
What is DataFrame?	          Table-like Pandas structure.
What is outlier?	            Abnormal data value.
What is Z-score?	            Distance from mean in standard deviations.
What is IQR?	                Spread between Q1 and Q3.
Why clean data?	              To improve accuracy and reliability.


Data Wrangling 1 vs Data Wrangling 2
Feature          	    Data Wrangling 1	                     Data Wrangling 2
Main Focus      	    Basic cleaning and handling data	     Advanced cleaning and outlier handling
Missing Values	      Basic handling	                       Advanced replacement methods
Encoding	            Usually included	                     Included
Duplicate Handling	  Basic	                                 More detailed
Outlier Detection	    Usually not covered deeply	           Z-score and IQR methods
Statistical Methods	  Less	                                 More
Data Transformation	  Basic	                                 Advanced
Complexity Level	    Beginner	                             Intermediate



Easy Real-Life Analogy
Data Wrangling 1

Like:

removing dust,
arranging books,
fixing broken labels.

Basic cleaning.

Data Wrangling 2

Like:

checking unusual books,
analyzing patterns,
removing abnormal items.

Advanced analysis and refinement.




What are Outliers?
Outliers are:

abnormal, unusual, or extreme data values that are very different from the rest of the dataset.

They do not follow the normal pattern of data.

Example of Outlier
Consider marks:
[45, 50, 48, 47, 46, 500]
Here:


most values are around 45–50


but 500 is extremely different


So:

500 is an outlier.


Why Outliers are Important?
Outliers can:


affect average (mean),


reduce machine learning accuracy,


create misleading graphs,


produce incorrect analysis.



Real-Life Examples of Outliers
DatasetOutlier ExampleStudent Marks1000 marks out of 100Salary Data₹5 crore salary among ₹30k salariesTemperature500°C weather readingBankingUnusual huge transaction

Types of Outliers
1. Global Outlier
Very far from all data.
Example:
[10, 12, 15, 18, 300]

2. Contextual Outlier
Abnormal in a specific condition.
Example:


5°C is normal in winter


5°C is abnormal in summer



How Outliers are Detected?
Main methods:
1. Z-Score Method
Formula:
z=x−μσz = \frac{x-\mu}{\sigma}z=σx−μ​xxxμ\muμσ\sigmaσz=x−μσ≈1.2z=\frac{x-\mu}{\sigma}\approx 1.2z=σx−μ​≈1.2Φ(z)≈88.5%\Phi(z)\approx 88.5\%Φ(z)≈88.5%
If:
|z| > 3
then value may be outlier.

2. IQR Method
Formula:
IQR=Q3−Q1IQR = Q_3 - Q_1IQR=Q3​−Q1​
Values outside:


Lower Bound


Upper Bound


are outliers.

Are data1.csv and data2.csv Cleaned or Uncleaned?
Based on your notebook:
DatasetTypedata1.csvUncleaned / Raw datasetdata2.csvUncleaned dataset with missing values and outliers

Why are They Uncleaned?
Because they contain:


missing values (NaN)


inconsistent values


categorical text data


possible outliers


noisy data


Example from your notebook:
df.isnull()
This checks missing values, meaning dataset is not fully clean.

What Happens After Wrangling?
After applying:


fillna()


dropna()


encoding


outlier removal


the dataset becomes:

cleaned dataset.


Simple Viva Answer
What are Outliers?

“Outliers are abnormal data values that are very different from other values in the dataset.”


Are data1.csv and data2.csv cleaned datasets?

“No, both are raw or uncleaned datasets because they contain missing values, categorical data, and outliers which require preprocessing.”