In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("data3.csv")
df

     CustomerID   Genre  Age  Annual Income  Spending Score
0             1    Male   19          19000               0
1             2    Male   35          20000               0
2             3  Female   26          43000               0
3             4  Female   27          57000               0
4             5    Male   19          76000               0
..          ...     ...  ...            ...             ...
194         195    Male   28          89000               0
195         196    Male   34          43000               0
196         197  Female   30          79000               0
197         198  Female   20          36000               0
198         199    Male   26          80000               0

[199 rows x 5 columns]

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())
enc_df

       0    1
0    0.0  1.0
1    0.0  1.0
2    1.0  0.0
3    1.0  0.0
4    0.0  1.0
..   ...  ...
194  0.0  1.0
195  0.0  1.0
196  1.0  0.0
197  1.0  0.0
198  0.0  1.0

[199 rows x 2 columns]

In [ ]:
df1 = df.join(enc_df)

df1

     CustomerID   Genre  Age  Annual Income  Spending Score    0    1
0             1    Male   19          19000               0  0.0  1.0
1             2    Male   35          20000               0  0.0  1.0
2             3  Female   26          43000               0  1.0  0.0
3             4  Female   27          57000               0  1.0  0.0
4             5    Male   19          76000               0  0.0  1.0
..          ...     ...  ...            ...             ...  ...  ...
194         195    Male   28          89000               0  0.0  1.0
195         196    Male   34          43000               0  0.0  1.0
196         197  Female   30          79000               0  1.0  0.0
197         198  Female   20          36000               0  1.0  0.0
198         199    Male   26          80000               0  0.0  1.0

[199 rows x 7 columns]

In [ ]:
del df1['Genre']

df1

     CustomerID  Age  Annual Income  Spending Score    0    1
0             1   19          19000               0  0.0  1.0
1             2   35          20000               0  0.0  1.0
2             3   26          43000               0  1.0  0.0
3             4   27          57000               0  1.0  0.0
4             5   19          76000               0  0.0  1.0
..          ...  ...            ...             ...  ...  ...
194         195   28          89000               0  0.0  1.0
195         196   34          43000               0  0.0  1.0
196         197   30          79000               0  1.0  0.0
197         198   20          36000               0  1.0  0.0
198         199   26          80000               0  0.0  1.0

[199 rows x 6 columns]

In [ ]:
df1.mean()

CustomerID          100.000000
Age                  30.306533
Annual Income     60633.165829
Spending Score        0.130653
0                     0.477387
1                     0.522613
dtype: float64

In [ ]:
df1.mean(axis=0)        # To find mean column wise

CustomerID          100.000000
Age                  30.306533
Annual Income     60633.165829
Spending Score        0.130653
0                     0.477387
1                     0.522613
dtype: float64

In [ ]:
df1.mean(axis=1)        # To find mean row wise

In [ ]:
df1.mean(axis=1)[0:4]   # To find mean row wise

0    3170.166667
1    3339.666667
2    7171.666667
3    9505.333333
dtype: float64

In [ ]:
df1.loc[:,'Age'].mean()  #To find mean of specific column

30.306532663316585

In [ ]:
df1.median()

CustomerID          100.0
Age                  29.0
Annual Income     59000.0
Spending Score        0.0
0                     0.0
1                     1.0
dtype: float64

In [ ]:
df1.mode()

     CustomerID   Age  Annual Income  Spending Score    0    1
0             1  35.0        80000.0             0.0  0.0  1.0
1             2   NaN            NaN             NaN  NaN  NaN
2             3   NaN            NaN             NaN  NaN  NaN
3             4   NaN            NaN             NaN  NaN  NaN
4             5   NaN            NaN             NaN  NaN  NaN
..          ...   ...            ...             ...  ...  ...
194         195   NaN            NaN             NaN  NaN  NaN
195         196   NaN            NaN             NaN  NaN  NaN
196         197   NaN            NaN             NaN  NaN  NaN
197         198   NaN            NaN             NaN  NaN  NaN
198         199   NaN            NaN             NaN  NaN  NaN

[199 rows x 6 columns]

In [ ]:
df1.std()

CustomerID           57.590508
Age                   7.465849
Annual Income     30848.949453
Spending Score        0.337871
0                     0.500748
1                     0.500748
dtype: float64

In [ ]:
df1.min()

CustomerID            1.0
Age                  18.0
Annual Income     15000.0
Spending Score        0.0
0                     0.0
1                     0.0
dtype: float64

In [ ]:
df1.max()

CustomerID           199.0
Age                   59.0
Annual Income     150000.0
Spending Score         1.0
0                      1.0
1                      1.0
dtype: float64

In [ ]:
df.groupby(['Genre'])['Age'].mean()

Genre
Female    29.884211
Male      30.692308
Name: Age, dtype: float64

In [ ]:
df.groupby(['Genre'])['Annual Income'].max()

Genre
Female    150000
Male      148000
Name: Annual Income, dtype: int64

In [ ]:
# Central Tendency and Data Analysis using Python – Complete Theory + Code Explanation

## 1. Introduction

This notebook explains:

* Data loading using Pandas
* Data inspection
* Data preprocessing
* One Hot Encoding
* Measures of Central Tendency
* Statistical Analysis
* GroupBy Operations

The notebook mainly uses:

* Pandas
* NumPy
* Scikit-learn

---

# 2. What is Central Tendency?

Central Tendency means finding the center value of data.

It helps us understand:

* Average behavior of data
* Typical value of dataset
* Overall trend of data

The three major measures are:

1. Mean
2. Median
3. Mode

---

# 3. Requirements to Run This Notebook

## Software Required

You need:

1. Python
2. Jupyter Notebook or Google Colab
3. Dataset file: `data3.csv`

---

## Python Libraries Required

Install these libraries:

```bash
pip install pandas
pip install numpy
pip install scikit-learn
```

---

# 4. What is Pandas?

Pandas is a Python library used for:

* Data analysis
* Data cleaning
* Data manipulation
* Statistical operations

Important structures in Pandas:

1. Series → Single column
2. DataFrame → Table format

---

# 5. What is NumPy?

NumPy is used for:

* Numerical operations
* Mathematical calculations
* Arrays
* Fast computation

---

# 6. What is Scikit-learn?

Scikit-learn is a Machine Learning library.

Used for:

* Data preprocessing
* Encoding
* Machine learning algorithms
* Model training

---

# 7. Step-by-Step Explanation of Notebook

---

# STEP 1: Import Libraries

```python
import pandas as pd
import numpy as np
```

## Line-by-Line Explanation

### `import pandas as pd`

* Imports Pandas library
* `pd` is an alias name
* Used for handling tables and datasets

### `import numpy as np`

* Imports NumPy library
* `np` is alias name
* Used for mathematical calculations

---

## Why do we import libraries?

Libraries contain pre-written functions.

Instead of writing everything manually, we use library functions.

---

# STEP 2: Read CSV File

```python
df = pd.read_csv("data3.csv")
df
```

---

## Line-by-Line Explanation

### `pd.read_csv()`

* Reads CSV file
* Converts it into DataFrame

### `"data3.csv"`

* Name of dataset file
* File should be in same folder as notebook

### `df =`

* Stores dataset into variable `df`

### `df`

* Displays complete dataset

---

## What is CSV?

CSV = Comma Separated Values

It stores tabular data.

Example:

```csv
Name,Age,Salary
Ali,22,30000
Sara,25,45000
```

---

# STEP 3: Dataset Information

```python
df.info()
```

---

## Purpose

Used to get:

* Number of rows
* Number of columns
* Data types
* Missing values
* Memory usage

---

## Example Output

```python
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries
```

---

## Important Terms

### Data Types

Common data types:

| Type   | Meaning         |
| ------ | --------------- |
| int    | Integer numbers |
| float  | Decimal numbers |
| object | String/text     |

---

# STEP 4: Statistical Summary

```python
df.describe()
```

---

## Purpose

Generates statistical summary.

---

## It Calculates

| Function | Meaning            |
| -------- | ------------------ |
| count    | Number of values   |
| mean     | Average            |
| std      | Standard deviation |
| min      | Minimum value      |
| max      | Maximum value      |
| 25%      | First quartile     |
| 50%      | Median             |
| 75%      | Third quartile     |

---

# STEP 5: One Hot Encoding

```python
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())
enc_df
```

---

# Theory of One Hot Encoding

Machine learning algorithms understand numbers, not text.

So categorical data like:

| Genre  |
| ------ |
| Male   |
| Female |

must be converted into numerical form.

This conversion is called Encoding.

---

## What is One Hot Encoding?

Converts categories into binary columns.

Example:

| Genre  |
| ------ |
| Male   |
| Female |

After encoding:

| Male | Female |
| ---- | ------ |
| 1    | 0      |
| 0    | 1      |

---

# Line-by-Line Explanation

### `from sklearn import preprocessing`

Imports preprocessing module.

### `OneHotEncoder()`

Creates encoder object.

### `df[['Genre']]`

Selects Genre column.

Double brackets return DataFrame.

### `fit_transform()`

* Learns categories
* Converts categories into encoded values

### `.toarray()`

Converts sparse matrix into normal array.

### `pd.DataFrame()`

Converts encoded array into table format.

### `enc_df`

Stores encoded data.

---

# STEP 6: Join Encoded Data

```python
df1 = df.join(enc_df)

df1
```

---

## Purpose

Combines original dataset with encoded columns.

---

## Line-by-Line Explanation

### `df.join(enc_df)`

Joins both DataFrames.

### `df1 =`

Stores result into new DataFrame.

---

# STEP 7: Delete Original Genre Column

```python
del df1['Genre']

df1
```

---

## Why delete Genre?

Because encoded columns already represent Genre.

Keeping both can create redundancy.

---

## Line-by-Line Explanation

### `del`

Deletes column.

### `df1['Genre']`

Specifies Genre column.

---

# STEP 8: Mean Calculation

```python
df1.mean()
```

---

# Theory of Mean

Mean = Average of values.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"\bar{x}=\frac{\sum x}{n}"}}

Where:

* Σx = Sum of all values
* n = Number of values

---

## Example

Numbers: 2, 4, 6

Mean:

(2 + 4 + 6) / 3 = 4

---

## Purpose

Calculates column-wise average.

---

# STEP 9: Mean Column Wise

```python
df1.mean(axis=0)
```

---

## What is Axis?

| Axis   | Meaning     |
| ------ | ----------- |
| axis=0 | Column wise |
| axis=1 | Row wise    |

---

## Line-by-Line Explanation

### `mean(axis=0)`

Calculates average for every column.

---

# STEP 10: Mean Row Wise

```python
df1.mean(axis=1)
```

---

## Purpose

Calculates average for every row.

Each row gets one average value.

---

# STEP 11: First Four Row Means

```python
df1.mean(axis=1)[0:4]
```

---

## Explanation

### `[0:4]`

Slicing operation.

Returns rows from index 0 to 3.

---

# STEP 12: Mean of Specific Column

```python
df1.loc[:,'Age'].mean()
```

---

## Line-by-Line Explanation

### `loc[]`

Used for label-based selection.

### `:`

Means all rows.

### `'Age'`

Selects Age column.

### `.mean()`

Calculates average age.

---

# STEP 13: Median

```python
df1.median()
```

---

# Theory of Median

Median = Middle value after sorting.

---

## Example

Data:

2, 4, 7, 9, 10

Median = 7

---

## Why Median is Important?

Median is less affected by outliers.

---

## Real Life Example

Used in:

* Salary analysis
* House price analysis

Because extreme values do not affect median much.

---

# STEP 14: Mode

```python
df1.mode()
```

---

# Theory of Mode

Mode = Most frequently occurring value.

---

## Example

1, 2, 2, 3, 4

Mode = 2

---

## Real Life Applications

Used in:

* Product demand analysis
* Customer preference analysis
* Survey analysis

---

# STEP 15: Standard Deviation

```python
df1.std()
```

---

# Theory of Standard Deviation

Measures spread of data.

Formula:

genui{"math_block_widget_always_prefetch_v2":{"content":"\sigma=\sqrt{\frac{\sum (x-\mu)^2}{N}}"}}

---

## Meaning

* Small std → data close to mean
* Large std → data widely spread

---

## Real Life Applications

Used in:

* Finance
* Risk analysis
* Quality control
* Data science

---

# STEP 16: Minimum Value

```python
df1.min()
```

---

## Purpose

Finds smallest value in each column.

---

# STEP 17: Maximum Value

```python
df1.max()
```

---

## Purpose

Finds largest value in each column.

---

# STEP 18: GroupBy Mean

```python
df.groupby(['Genre'])['Age'].mean()
```

---

# Theory of GroupBy

GroupBy splits data into groups.

Then operations are performed on each group.

---

## What This Code Does

* Groups data by Genre
* Calculates average age for each gender

---

## Step-by-Step Explanation

### `groupby(['Genre'])`

Creates groups based on Genre.

### `['Age']`

Selects Age column.

### `.mean()`

Calculates average age.

---

# STEP 19: GroupBy Maximum

```python
df.groupby(['Genre'])['Annual Income'].max()
```

---

## Purpose

Finds maximum annual income for each gender.

---

# Complete Workflow of Notebook

## Step-by-Step Flow

1. Import libraries
2. Load dataset
3. Inspect data
4. Generate statistical summary
5. Encode categorical data
6. Join encoded data
7. Remove original categorical column
8. Perform statistical analysis
9. Apply mean, median, mode
10. Find standard deviation
11. Find min and max values
12. Perform groupby analysis

---

# Real Life Applications of This Notebook

## 1. Business Analytics

Used to analyze:

* Customer income
* Spending patterns
* Gender-based analysis

---

## 2. Data Science

Used before machine learning.

Helps clean and preprocess data.

---

## 3. Banking

Used for:

* Customer segmentation
* Loan analysis
* Risk analysis

---

## 4. Marketing

Used to analyze:

* Customer behavior
* Product demand
* Target audience

---

# Important Viva Questions

## Basic Questions

### 1. What is DataFrame?

A tabular data structure in Pandas.

---

### 2. What is One Hot Encoding?

Converts categorical data into binary numerical format.

---

### 3. Difference between Mean and Median?

| Mean                 | Median        |
| -------------------- | ------------- |
| Average value        | Middle value  |
| Affected by outliers | Less affected |

---

### 4. What is GroupBy?

Used to split data into groups and apply operations.

---

### 5. Why is preprocessing required?

To clean and convert data into machine-readable format.

---

### 6. What is Standard Deviation?

Measures spread of data.

---

# Common Errors While Running

## Error 1

```python
FileNotFoundError
```

### Reason

CSV file not found.

### Solution

Place CSV file in same folder.

---

## Error 2

```python
ModuleNotFoundError
```

### Reason

Library not installed.

### Solution

Install libraries using pip.

---

# Final Summary

This notebook performs:

* Data loading
* Data preprocessing
* Encoding
* Statistical analysis
* Central tendency calculations
* GroupBy operations

Main concepts covered:

* Mean
* Median
* Mode
* Standard deviation
* Encoding
* DataFrames
* GroupBy

This is an important foundation for:

* Data Science
* Machine Learning
* Data Analytics
* Artificial Intelligence



1. Mean (Average)

Mean is the sum of all values divided by total number of values.

Formula:

x
ˉ
=
n
∑x
	​


Where:

x
ˉ
 = Mean
∑x = Sum of all values
n = Total number of values
Example

Values: 2, 4, 6

Mean:

3
2+4+6
	​

=4
2. Median

Median is the middle value after arranging data in ascending order.

Formula
If number of observations is odd:

Median=(
2
n+1
	​

)
th
 value

If number of observations is even:

Median=
2
(
2
n
	​

)
th
 value+(
2
n
	​

+1)
th
 value
	​


Where:

n = Total number of observations
Example

Data: 2, 4, 6, 8, 10

Median = 6

3. Mode

Mode is the value that occurs most frequently in the dataset.

Formula:

Mode=Most Frequently Occurring Value

Example

Data: 1, 2, 2, 3, 4

Mode = 2